### PR TITLE
Make Massive Shields Up

### PR DESCRIPTION
**Pull request by beccabunny**
Please devs consider this

### CODE REVIEW

**Comment by Anarchist2** [comment]
Please update the README.md and about.txt accordingly.

**Comment by Anarchist2** [comment]
In response to the massive amounts of PRs I've gotten for this, I've decided to create an experimental branch. I'll let this PR stay open because of the grandfather clause, but please redirect all PRs to the experimental branch.

**Comment by beccabunny** [comment]
-move #experimental-branch 3

**Comment by beccabunny** [comment]
Why is James not working, do I need a bacitrician license?

**Pull request merged**
